---

- name: Configure global settings
  template:
    src: "mongod.conf.j2"
    dest: "{{ mongodb__configfile }}"
    backup: yes
    owner: root
    group: root
    mode: 0644
  notify: restart mongodb-server



- name: Start mongod daemon
  service:
    name: mongod
    state: started
    # enabled: true
